### ISSUE TITLE
Sorbet/AllowIncompatibleOverride inspection error

### ISSUE THREAD

**Issue by jakebrady5** [Shopify/rubocop-sorbet#171]
When parsing a signature resembling `sig { override(allow_incompatible: true).void }` the inspection errors as follows:

```
NoMethodError:
  undefined method `each_node' for nil:NilClass
# ./lib/rubocop/cop/sorbet/signatures/allow_incompatible_override.rb:39:in `sig?'
# ./lib/rubocop/cop/sorbet/signatures/allow_incompatible_override.rb:32:in `allow_incompatible_override?'
# ./lib/rubocop/cop/sorbet/signatures/allow_incompatible_override.rb:41:in `on_send'
```

Test [case](https://github.com/jakebrady5/rubocop-sorbet/blob/override-parser-error/spec/rubocop/cop/sorbet/signatures/allow_incompatible_override_spec.rb#L17) added on this [branch](https://github.com/jakebrady5/rubocop-sorbet/tree/override-parser-error) reproduces the error.

`rspec ./spec/rubocop/cop/sorbet/signatures/allow_incompatible_override_spec.rb:17`

Seems potentially related to a recent [refactor](https://github.com/Shopify/rubocop-sorbet/pull/150)?

**Comment by willvictoria** [comment]
+1, seeing this error when upgrading from 0.7.0 -> 0.7.2

**Comment by KaanOzkan** [comment]
This should be fixed in v0.7.3 https://github.com/Shopify/rubocop-sorbet/releases/tag/v0.7.3
